# Site/SEO settings
email: 
permalink: /:year/:month/:day/:title/
google_analytics: 

title: SonderBear's World
description: 
url: ""
baseurl: ""
twitter_username: 
default_img: 

# Profile settings
name: SonderBear
profile_img: https://pic.images.ac.cn/image/5e7a6db282682
profile: 互联网搬砖者/阿尔茨海默疑似患者
social:
  github: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
